use_modular_headers!

platform :ios, '14.0'

target 'VANavigator_Example' do
  inhibit_all_warnings!
  pod 'VANavigator', :path => '../'
  pod 'VATextureKitRx', '~> 2.0.3'
  pod 'Swiftional', '~> 2.0.0'
  pod 'RxKeyboard', '~> 2.0.0'

  target 'VANavigator_ExampleTests' do
    inhibit_all_warnings!
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
    if target.name == "Texture"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AS_ENABLE_TEXTNODE=1']
      end
    end
    if target.name == "VATextureKit"
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited) -D AS_ENABLE_TEXTNODE2']
      end
    end
  end
end
